name       : kquickcharts
version    : 5.87.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/kquickcharts-5.87.0.tar.xz : 6833af044f9150fba61ac09fa5cd2d67860f9c7c6ed0625d8dee2618398da4b7
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
