name       : kquickcharts
version    : 5.75.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kquickcharts-5.75.0.tar.xz : d2595bf1f8b6c5c46961cb95feed2b1f0f16b377ef65cb6fb12bbfcec0c81b82
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
