name       : kquickcharts
version    : 5.65.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kquickcharts-5.65.0.tar.xz : f9ab7697845c872d25e998f2b213d4c32c0b2ccdef99de018dc486d1c4a98388
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
