name       : kquickcharts
version    : 5.80.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kquickcharts-5.80.0.tar.xz : 962ed2b22ccac8ae900827bc41581efea546b833495869d3e3ccc5795314c74d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
