name       : kquickcharts
version    : 5.79.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kquickcharts-5.79.0.tar.xz : cea84ce7f9aad891477c916a875e82a142b0f33ee457f9eadfcaf77e701d2add
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
