name       : kquickcharts
version    : 5.78.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kquickcharts-5.78.0.tar.xz : 1762b927e8fbaa24cb20425dfcdf875190000f357d1f3637dd580bc2c75d05ff
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
