name       : kquickcharts
version    : 5.69.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kquickcharts-5.69.0.tar.xz : a532ef82542a58d61dc5934835393e8de0f2ec8a3058096f46c2b7ba0ae92b16
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
