name       : kquickcharts
version    : 5.96.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kquickcharts-5.96.0.tar.xz : 72e096dad12cadeb2f89bebebdf906d5312dc2f8479ff36750ae8b33bbaba9e9
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : A QtQuick plugin providing high-performance charts
description: |
    A QtQuick plugin providing high-performance charts
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
